/**
 * 易经 64 卦数据核心骨架
 * 由 Gemini 维护结构，用户维护内容
 */
const guaData = {
    "01": {
        name: "01. 乾为天",
        quote: "这里填梁冬金句",
        state: "这里填详细意象",
        warn: "这里填避坑指南",
        advice: "这里填建议",
        yao: ["初九:...", "九二:...", "九三:...", "九四:...", "九五:...", "上九:..."]
    },
    "02": {
        name: "02. 坤为地",
        quote: "",
        state: "",
        warn: "",
        advice: "",
        yao: ["初六:...", "六二:...", "六三:...", "六四:...", "六五:...", "上六:..."]
    },
    // --- 快速填充区 (请按照此格式继续向下复制) ---
    // 你可以一次填 5 个，然后刷新网页检查
    "03": { name: "03. 水雷屯", quote: "", state: "", warn: "", advice: "", yao: [] },
    "04": { name: "04. 山水蒙", quote: "", state: "", warn: "", advice: "", yao: [] },
    "05": { name: "05. 水天需", quote: "", state: "", warn: "", advice: "", yao: [] },
    "06": { name: "06. 天水讼", quote: "", state: "", warn: "", advice: "", yao: [] },
    "07": { name: "07. 地水师", quote: "", state: "", warn: "", advice: "", yao: [] },
    "08": { name: "08. 水地比", quote: "", state: "", warn: "", advice: "", yao: [] },
    "09": { name: "09. 风天小畜", quote: "", state: "", warn: "", advice: "", yao: [] },
    "10": { name: "10. 天泽履", quote: "", state: "", warn: "", advice: "", yao: [] },
    "11": { name: "11. 地天泰", quote: "", state: "", warn: "", advice: "", yao: [] },
    "12": { name: "12. 天地否", quote: "", state: "", warn: "", advice: "", yao: [] },
    "13": { name: "13. 天火同人", quote: "", state: "", warn: "", advice: "", yao: [] },
    "14": { name: "14. 火天大有", quote: "", state: "", warn: "", advice: "", yao: [] },
    "15": { name: "15. 地山谦", quote: "", state: "", warn: "", advice: "", yao: [] },
    "16": { name: "16. 雷地豫", quote: "", state: "", warn: "", advice: "", yao: [] },
    "17": { name: "17. 泽雷随", quote: "", state: "", warn: "", advice: "", yao: [] },
    "18": { name: "18. 山风蛊", quote: "", state: "", warn: "", advice: "", yao: [] },
    "19": { name: "19. 地泽临", quote: "", state: "", warn: "", advice: "", yao: [] },
    "20": { name: "20. 风地观", quote: "", state: "", warn: "", advice: "", yao: [] },
    "21": { name: "21. 火雷噬嗑", quote: "", state: "", warn: "", advice: "", yao: [] },
    "22": { name: "22. 山火贲", quote: "", state: "", warn: "", advice: "", yao: [] },
    "23": { name: "23. 山地剥", quote: "", state: "", warn: "", advice: "", yao: [] },
    "24": { name: "24. 地雷复", quote: "", state: "", warn: "", advice: "", yao: [] },
    "25": { name: "25. 天雷无妄", quote: "", state: "", warn: "", advice: "", yao: [] },
    "26": { name: "26. 山天大畜", quote: "", state: "", warn: "", advice: "", yao: [] },
    "27": { name: "27. 山雷颐", quote: "", state: "", warn: "", advice: "", yao: [] },
    "28": { name: "28. 泽风大过", quote: "", state: "", warn: "", advice: "", yao: [] },
    "29": { name: "29. 坎为水", quote: "", state: "", warn: "", advice: "", yao: [] },
    "30": { name: "30. 离为火", quote: "", state: "", warn: "", advice: "", yao: [] },
    "31": { name: "31. 泽山咸", quote: "", state: "", warn: "", advice: "", yao: [] },
    "32": { name: "32. 雷风恒", quote: "", state: "", warn: "", advice: "", yao: [] },
    "33": { name: "33. 天山遁", quote: "", state: "", warn: "", advice: "", yao: [] },
    "34": { name: "34. 雷天大壮", quote: "", state: "", warn: "", advice: "", yao: [] },
    "35": { name: "35. 火地晋", quote: "", state: "", warn: "", advice: "", yao: [] },
    "36": { name: "36. 地火明夷", quote: "", state: "", warn: "", advice: "", yao: [] },
    "37": { name: "37. 风火家人", quote: "", state: "", warn: "", advice: "", yao: [] },
    "38": { name: "38. 火泽睽", quote: "", state: "", warn: "", advice: "", yao: [] },
    "39": { name: "39. 水山蹇", quote: "", state: "", warn: "", advice: "", yao: [] },
    "40": { name: "40. 雷水解", quote: "", state: "", warn: "", advice: "", yao: [] },
    "41": { name: "41. 山泽损", quote: "", state: "", warn: "", advice: "", yao: [] },
    "42": { name: "42. 风雷益", quote: "", state: "", warn: "", advice: "", yao: [] },
    "43": { name: "43. 泽天夬", quote: "", state: "", warn: "", advice: "", yao: [] },
    "44": { name: "44. 天风姤", quote: "", state: "", warn: "", advice: "", yao: [] },
    "45": { name: "45. 泽地萃", quote: "", state: "", warn: "", advice: "", yao: [] },
    "46": { name: "46. 地风升", quote: "", state: "", warn: "", advice: "", yao: [] },
    "47": { name: "47. 泽水困", quote: "", state: "", warn: "", advice: "", yao: [] },
    "48": { name: "48. 水风井", quote: "", state: "", warn: "", advice: "", yao: [] },
    "49": { name: "49. 泽火革", quote: "", state: "", warn: "", advice: "", yao: [] },
    "50": { name: "50. 火风鼎", quote: "", state: "", warn: "", advice: "", yao: [] },
    "51": { name: "51. 震为雷", quote: "", state: "", warn: "", advice: "", yao: [] },
    "52": { name: "52. 艮为山", quote: "", state: "", warn: "", advice: "", yao: [] },
    "53": { name: "53. 风山渐", quote: "", state: "", warn: "", advice: "", yao: [] },
    "54": { name: "54. 雷泽归妹", quote: "", state: "", warn: "", advice: "", yao: [] },
    "55": { name: "55. 雷火丰", quote: "", state: "", warn: "", advice: "", yao: [] },
    "56": { name: "56. 火山旅", quote: "", state: "", warn: "", advice: "", yao: [] },
    "57": { name: "57. 巽为风", quote: "", state: "", warn: "", advice: "", yao: [] },
    "58": { name: "58. 泽为泽", quote: "", state: "", warn: "", advice: "", yao: [] },
    "59": { name: "59. 风水涣", quote: "", state: "", warn: "", advice: "", yao: [] },
    "60": { name: "60. 水泽节", quote: "", state: "", warn: "", advice: "", yao: [] },
    "61": { name: "61. 风泽中孚", quote: "", state: "", warn: "", advice: "", yao: [] },
    "62": { name: "62. 雷山小过", quote: "", state: "", warn: "", advice: "", yao: [] },
    "63": { name: "63. 水火既济", quote: "", state: "", warn: "", advice: "", yao: [] },
    "64": { name: "64. 火水未济", quote: "", state: "", warn: "", advice: "", yao: [] }
};

console.log("数据加载成功，当前卦数：", Object.keys(guaData).length);
